name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: sherqiye23
          outputs: |
            dist/github-contribution-grid-snake.svg
          snake_color: '#00bfff'          # 💙 mavi ilan
          background_color: '#0d1117'     # 🌑 dark mode background

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
